sudo: required

language: c++

services:
  - docker

before_install:
  - docker pull trinhpham/xiaomi-r3g-openwrt-builder

script:
  - docker run -t --name=trinhpham_ci --rm trinhpham/xiaomi-r3g-openwrt-builder
